feat: change workflow 2

diff --git a/.github/workflows/http-request-workflow-2.yml b/.github/workflows/http-request-workflow-2.yml
--- a/.github/workflows/http-request-workflow-2.yml
+++ b/.github/workflows/http-request-workflow-2.yml
@@ -15,19 +15,17 @@ on:
 jobs:
   run-tests:
     runs-on: ubuntu-latest
+    outputs:
+        results: ${{ steps.start.outputs }}
     strategy:
       fail-fast: false
       matrix:
         containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
     steps:
         - name: start
+          id: start
           shell: bash
-          run: |
-            if [ ${{ matrix.containers }} % 2 == 0 ]; then
-              exit 0
-            else
-              exit 1
-            fi
+          run: exit 1
 
   check_test_results:
     needs: [run-tests]
@@ -35,18 +33,21 @@ jobs:
     runs-on: ubuntu-latest
     if: ${{ always() }}
     steps:
-      - name: Comment success
-        if: ${{ job.status }}" == "success"
-        uses: thollander/actions-comment-pull-request@v2
-        with:
-          message: "✅ Merge - Successed \n https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-          pr_number: ${{ inputs.PR }}
-          comment_tag: auto_merge
+        - name: Echo outputs
+          shell: bash
+          run: echo ${{ needs.run-tests.outputs.results }}
+      # - name: Comment success
+      #   if: ${{ job.status }}" == "success"
+      #   uses: thollander/actions-comment-pull-request@v2
+      #   with:
+      #     message: "✅ Merge - Successed \n https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+      #     pr_number: ${{ inputs.PR }}
+      #     comment_tag: auto_merge
 
-      - name: Comment failed
-        if: ${{ job.status }}" != "success"
-        uses: thollander/actions-comment-pull-request@v2
-        with:
-          message: "❌ Merge - Failed \n https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-          pr_number: ${{ inputs.PR }}
-          comment_tag: auto_merge
+      # - name: Comment failed
+      #   if: ${{ job.status }}" != "success"
+      #   uses: thollander/actions-comment-pull-request@v2
+      #   with:
+      #     message: "❌ Merge - Failed \n https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+      #     pr_number: ${{ inputs.PR }}
+      #     comment_tag: auto_merge
